[build]
  command = "git clone https://github.com/flutter/flutter.git -b stable --depth 1 && ./flutter/bin/flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "stable"
