name: Deploy Web to GitHub Pages

on:
  push:
    branches:
      - main # change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Flutter ğŸš€
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # flutter-version: '3.19.0' # Optional: specify version

      - name: Install dependencies ğŸ“¦
        run: flutter pub get

      - name: Build Web ğŸ—ï¸
        run: flutter build web --release --base-href "/store/"

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web # The folder the action should deploy.
          branch: gh-pages # The branch the action should deploy to.
